#!/bin/bash
#Upgrade hugin
add-apt-repository -y ppa:hugin/hugin-builds

#mpeg repos
add-apt-repository -y ppa:jonathonf/ffmpeg-3
add-apt-repository -y ppa:jonathonf/tesseract

#nvidia repos
add-apt-repository -y ppa:graphics-drivers/ppa

#get the docker official GPG key
#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
